### ISSUE TITLE
On Hot Restart a new WebSocket connection is created without disposing the old one.

### ISSUE THREAD

**Issue by Morthor** [infitio/flutter_socket_io#6]
On my Widget I run the following "initSockets" method to initiate the connection to socket.io:

### Flutter code
```dart
@override
void initState() {
  super.initState();
  initSockets();
}

@override
void dispose() {
  subscription.cancel();
  socketIOManager.clearInstance(socket);
  super.dispose();
}

void initSockets() async {
  print('initSockets');

  socket = await socketIOManager.createInstance(localServerAddress());
  socket.onConnect((data){
    print("connected...");
  });
  socket.on("top_events", (data){
    print("top_events");
  });
  socket.onDisconnect((data){
    print('disconnected from socket.io');
  });
  socket.onReconnect((data){
    print('reconnected to socket.io');
  });
  socket.connect();
}
```

If I do a Hot Restart a new connection is created without disposing of the old one. I have to Terminate the app and start it again, and only when the app terminates do the web socket connections get disconnected.

### NodeJS server log 
(This is one continuous log without restarts. It's separated into chunks to mention what is being done on the Flutter App.)
#### NodeJS Server start

> listening on *:3003
> User connected
> iZguUkmta-LEqu5DAAAA joined top_events.

Hot Restart Flutter App

> User connected
> XY-djcCpulwsluHWAAAB joined top_events.

Hot Restart Flutter App

> User connected
> ZhFEKkq9kzsv9duuAAAC joined top_events.

Hot Restart Flutter App

> User connected
> pEyRC6IZ4utNzr0RAAAD joined top_events.

Terminated Flutter App

> User pEyRC6IZ4utNzr0RAAAD disconnected
> User iZguUkmta-LEqu5DAAAA disconnected
> User XY-djcCpulwsluHWAAAB disconnected
> User ZhFEKkq9kzsv9duuAAAC disconnected

Built Flutter App

> User connected
> LffWd5d2YU3haGF9AAAE joined top_events.

Hot Restart Flutter App

> User connected
> kPtgi5YNkujpp59CAAAF joined top_events.

Hot Restart Flutter App

> User connected
> HLJcRi2Q8ZdpxSTdAAAG joined top_events.

How can I make sure the old connection is disconnected on Hot Restart?

**Comment by tiholic** [comment]
@Morthor thanks for pointing out.

This is what I have in mind... you can call `newInstance` which will return an existing SocketIO instance if you are invoking with the same parameters.

If someone needs to forcefully create a new instance, that will be possible by sending a new argument `bool enforceNew` to `SocketIOManager.createInstance`

**Comment by liuyun1014** [comment]
Willing to share how your sockets are globally introduced

**Comment by tiholic** [comment]
@liuyun1014 sorry, I didn't understand your comment

**Comment by lhcdims** [comment]
My work around for this problem:

1. Create an array on the socket.io server, which stores all sockets connected, each element of the array should contain at least:
(a) the socket.id
(b) the last time that a heart beat is received.

2. On the client side, create a timer that send a heartbeat to the server every X seconds.

3. On the server side, when a heart beat is received, update 1(b).

4. On the server side, create a timer that read the whole array every X seconds, if ANY (b) is more than Y seconds (Y >= X * 3) , disconnect that socket from the server side.

Now for every hot restart and/or hot reload whatever, since the timer stated in point 2 can only be run once, the server can only receive heart beat from ONE AND ONLY ONE socket of this particular client.  The other sockets for this client will be disconnected from the server side sooner or later, depending on the values of X and Y.  (I usually set X = 10 and Y = 30)

**Comment by zcr1** [comment]
A simpler workaround would be to either expose a method to a) disconnect all sockets or b) get existing sockets.

**Comment by zcr1** [comment]
I ended up adding a method to disconnect all existing sockets that I call before connecting.

Added to `SwiftAdharaSocketIOPlugin.swift` handle function
```
case "clearAll":
    var i = 0
                
    while (i < currentIndex - 1){
        instances[i]?.socket.disconnect()
        instances[i] = nil
         i += 1
     }
                    
    result(nil);
```

Added to `Manager.dart`
```
Future clearAll() async {
    await _channel.invokeMethod('clearAll', {});
    _sockets.clear();
}
```

**Comment by Appjak34** [comment]
When I restart my flutter app, another instance of a socket is created, but the previous one is not disconnected nor does it callback the dispose. 
What can I do to send disconnect to the server from my flutter application and not create another instance of socket ?

**Comment by rajputvarun591** [comment]
Same problem i am facing. also i want to know how to continuously listen for a socket event like for receive a chat message.

**Comment by tiholic** [comment]
This has been fixed with 1.0.0 release

https://pub.dev/packages/adhara_socket_io/versions/1.0.0

**Comment by AkshayJainX** [comment]
> @Morthor thanks for pointing out.
> 
> This is what I have in mind... you can call `newInstance` which will return an existing SocketIO instance if you are invoking with the same parameters.
> 
> If someone needs to forcefully create a new instance, that will be possible by sending a new argument `bool enforceNew` to `SocketIOManager.createInstance`

Can you please share the answer for socket_io_client: ^1.0.1 plugin. Still facing the issue...

**Comment by AkshayJainX** [comment]
> This has been fixed with 1.0.0 release
> 
> https://pub.dev/packages/adhara_socket_io/versions/1.0.0

Can you please help in bug fixing for socket_io_client: ^1.0.1 plugin

**Comment by santosh2221994** [comment]
> > This has been fixed with 1.0.0 release
> > https://pub.dev/packages/adhara_socket_io/versions/1.0.0
> 
> Can you please help in bug fixing for socket_io_client: ^1.0.1 plugin

As https://pub.dev/packages/adhara_socket_io/versions/1.0.0 is not null safety. please help me out as it creating so many instances in the server and thus server sometimes got hang... please help me out in this plugin
